apiVersion: v2
name: pullsecret-patcher
description: A Helm chart for pullsecret-patcher
type: application
version: 0.1.0
appVersion: "v0.14"
home: https://github.com/thames-digital/helm-imagepullsecret-patcher
sources:
  - https://github.com/thames-digital/helm-imagepullsecret-patcher
maintainers:
  - name: thames-digital
