# Add here base64 json formatted of your credentials/
# example:
# {"auths":{"https://index.docker.io/v1/":{"auth":"Base64_of_your_credentials"}},"credsStore":"ecr-login"}
# Base64_of_your_credentials = UserName:Password
dockerconfigjson: 
secretName: image-pull-secret-src

replicaCount: 1

image:
  repository: "quay.io/titansoft/imagepullsecret-patcher"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "imagepullsecret-patcher"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: 
   limits:
     cpu: 0.2m
     memory: 30Mi
   requests:
     cpu: 0.1m
     memory: 15Mi

nodeSelector: {}

tolerations: []

affinity: {}
