{{- if not .Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "pullsecret-patcher.labels" . | nindent 4 }}
data: 
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
{{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pullsecret-patcher.fullname" . }}
  labels:
    {{- include "pullsecret-patcher.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pullsecret-patcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pullsecret-patcher.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: true 
      serviceAccountName: {{ include "pullsecret-patcher.serviceAccountName" . }}
      containers:
        - name: {{ include "pullsecret-patcher.serviceAccountName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: CONFIG_FORCE
              value: "true"
            - name: CONFIG_DEBUG
              value: "false"
            - name: CONFIG_ALLSERVICEACCOUNT
              value: "true"
            - name: CONFIG_DOCKERCONFIGJSONPATH
              value: "/app/secrets/.dockerconfigjson"
          volumeMounts:
            - name: src-dockerconfigjson
              mountPath: "/app/secrets"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: src-dockerconfigjson
          secret: 
            secretName: {{ .Values.secretName }}